# Generated by Django 3.1.6 on 2021-02-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='token',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='users',
            name='mail',
            field=models.EmailField(max_length=254),
        ),
    ]
