from token import Token

# creating Authentication class
# this will be used by the login function that will be created in views.py
# this class will include methods for checking username and password 
# the class will also have to store the token


class Authentication:
    USERNAME = 'TDteam3'
    PASSWORD = 'whatever'
    
    def __init__(self, username, password):
        if Authentication.is_authentication_valid(username, password):
            # below will be stored the token that is generated by the TokenGenerator class
            token_str = Token.generate_token(username, password)
            self.token = {token_str}
        else:
            self.token = None

    @staticmethod
    def is_authentication_data_valid(username, password):
        if username == Authentication.USERNAME and password == Authentication.PASSWORD:
            return True
        else:
            return False

    def is_token_valid(self, token_in_json):  # parameter will be the 'token' value of json file
        if {token_in_json} == self.token:
            if not Token.is_token_expired(token_in_json):
                return True
            else:
                return False  # must return a "session expired" message
        else:
            return False  # not existing token
            # the views function in this case must return an error


